---
title: "Access to Care - Dashboard"
format: dashboard
server: shiny
---


```{r}
#| context: setup
library(accesstocare)
library(ggplot2)
library(ggiraph)
library(usmap)
library(dplyr)
library(shiny)
library(gt)
library(bslib)
library(bsicons)

state_list <- c("All US", us_states$state_name)

us_choices <- c("Above model", "Below model", "No. of Hospitals", "Population")
state_choices <- c( "Model", "No. of Hospitals", "Population")

```

# State info

## Row {height=30%}

```{r}
selectInput(
  inputId = "state",
  label = "Select a State:",
  choices = state_list,
  selected = "All US", 
  selectize = FALSE
  )
```

```{r}
value_box(
  title = "Population",
  value = textOutput("population"),
  showcase = bs_icon("person"),
  theme = "blue"
)
```

```{r}
value_box(
  title = "Hospitals",
  value = textOutput("hospitals"),
  showcase = bs_icon("hospital"),
  theme = "teal"
)
```

```{r}
value_box(
  title = "Counties",
  value = textOutput("counties"),
  showcase = bs_icon("geo-alt"),
  theme = "green"
)
```

```{r}
value_box(
  title = "Underserved",
  value = textOutput("underserved"),
  showcase = bs_icon("clipboard2-pulse"),
  theme = "pink"
)
```

## Row {height=70%}

### {.sidebar}

```{r}
actionButton(
  inputId = "us",
  label = "All US"
  )

radioButtons(
  inputId = "view",
  label = "Select a view:",
  choices = us_choices, 
  inline = TRUE
  )
```

### Column


```{r}

girafeOutput("usmap")
```

```{r}
#| context: server
#| 
sel_state <- reactive({
  if(input$state == "All US") {
    us_states
  } else {
    us_states %>% 
      filter(state_name == input$state) 
  }
})

sel_county <- reactive({
  if(input$state == "All US") {
    us_counties
  } else {
    us_counties %>% 
      filter(state_name == input$state) 
  }
})


output$population <- renderText({
  sel_state() %>% 
    summarise(sum(population)) %>% 
    pull() %>%
    format_number()
    })


output$hospitals <- renderText({
  sel_state() %>%
    summarise(sum(hospitals)) %>%
    pull() |> 
    format_number() 
  })

output$counties <- renderText({
  sel_county() %>%
    count() %>% 
    pull() %>% 
    format_number() 
  })

output$underserved <- renderText({
  sel_county() %>%
    filter(pred_status == "below") %>% 
    count() %>% 
    pull() 
  })

output$usmap <- renderGirafe({
  
  x_width <- 10
  
  vr <- "population"
  
  if(input$view == "Population") vr <- "population"
  if(input$view == "No. of Hospitals") vr <- "hospitals"
  if(input$view == "Above model") vr <- "above"
  if(input$view == "Below model") vr <- "below"
  if(input$view == "Model") vr <- "model"
    
  if(input$state == "All US") {
    gp <- atc_plot_us_map(vr)
  } else {
    
    
    # x_width <- usmap::us_map("counties") %>% 
    #   filter(full == input$state) %>% 
    #   summarise(
    #     max_x = max(x), min_x = min(x),
    #     max_y = max(y), min_y = min(y)
    #   ) %>% 
    #   mutate(
    #     x_size = max_x - min_x,
    #     y_size = max_y - min_y,
    #     xy = x_size/y_size * 10
    #   ) %>% 
    #   pull(xy)
    
    gp <- atc_plot_state_map(input$state, vr)
  }
  
  girafe(
    ggobj = gp,
    width_svg = x_width, 
    height_svg = 5, 
    options = list(
      opts_selection(type = "single", only_shiny = FALSE),
      opts_tooltip(opacity = 0.7), 
      opts_sizing(FALSE)
      )
    )  
})

```

